version: '3.5'
services:
    nginx:
      image: ${COMPOSE_PROJECT_NAME}-nginx:latest
      build:
        context: ./docker/
        args:
          BUILD_ARGUMENT_ENV: dev
        dockerfile: ./nginx/Dockerfile
      container_name: ${COMPOSE_PROJECT_NAME}-nginx
      restart: always
      ports:
        - "${WEB_PORT_HTTP}:80"
        - "${WEB_PORT_SSL}:443"
      volumes:
        - ./:/var/www/html:ro,cached
        - ./storage/app/public:/var/www/html/public/storage:ro,cached
      depends_on:
        - laravel
      networks:
        - parbocloud
    laravel: &laravel-template
      image: ${COMPOSE_PROJECT_NAME}-laravel:latest
      build:
        context: .
        args:
          BUILD_ARGUMENT_ENV: dev
          HOST_UID: ${HOST_UID}
          HOST_GID: ${HOST_GID}
          XDEBUG_CONFIG: ${XDEBUG_CONFIG}
        dockerfile: ./Dockerfile
      container_name: ${COMPOSE_PROJECT_NAME}-laravel
      volumes:
        - ./:/var/www/html:cached
        - ./storage/app/public:/var/www/html/public/storage:cached
      networks:
        - parbocloud

    ### Cron tasks
    supervisord:
      <<: *laravel-template
      container_name: ${COMPOSE_PROJECT_NAME}-supervisord
      expose: []
      command: ["/usr/bin/supervisord"]

networks:
  parbocloud:
    name: parbocloud
    driver: bridge
